meta_product_name: "Restaurant du Pont"
meta_title: "Restaurant du Pont - Basse - Goulaine, France"
meta_description: "Nous vous proposons de découvrir une cuisine audacieuse, où les saveurs et les textures sont judicieusement associées. Dans une ambiance chic et décontractée, laissez-vous séduire par nos mets et vins subtilement pensés pour un voyage culinaire inattendu..."
meta_image: "salle.jpg"
