meta_product_name: "Restaurant du Pont"
meta_title: "Restaurant du Pont - Basse-Goulaine, Cuisine Gastronomique aux environs de Nantes"
meta_description: "Nous vous proposons de découvrir une cuisine audacieuse, où les saveurs et les textures sont judicieusement associées."
meta_image: "salle.jpg"
